//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonBazou_ModManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Handler {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Handler() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonBazou_ModManager.Resources.Handler", typeof(Handler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Is this the correct location of your game?.
        /// </summary>
        internal static string Correct_Location {
            get {
                return ResourceManager.GetString("Correct_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t Auto-Locate Install Folder!.
        /// </summary>
        internal static string Could_Not_Locate_Install_Folder {
            get {
                return ResourceManager.GetString("Could_Not_Locate_Install_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading Mod List.
        /// </summary>
        internal static string Error_While_Loading_Mod_List {
            get {
                return ResourceManager.GetString("Error_While_Loading_Mod_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retrieving changelog!.
        /// </summary>
        internal static string Error_While_Retrieving_Changelog {
            get {
                return ResourceManager.GetString("Error_While_Retrieving_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Manager.
        /// </summary>
        internal static string Mod_Manager {
            get {
                return ResourceManager.GetString("Mod_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Game&apos;s Install Location in the Folder Browser!.
        /// </summary>
        internal static string Select_Game_Install_Location {
            get {
                return ResourceManager.GetString("Select_Game_Install_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Mon Bazou Folder!.
        /// </summary>
        internal static string Select_Mon_Bazou_Folder {
            get {
                return ResourceManager.GetString("Select_Mon_Bazou_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Folder.
        /// </summary>
        internal static string Wrong_Folder {
            get {
                return ResourceManager.GetString("Wrong_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the wrong folder!.
        /// </summary>
        internal static string You_Have_Selected_The_Wrong_Folder {
            get {
                return ResourceManager.GetString("You_Have_Selected_The_Wrong_Folder", resourceCulture);
            }
        }
    }
}
